Slight tweak to Lens.root doc
obrok/lens pull request #7
Opened 2017-01-03 08:33 UTC by sebastian

I am not fully convinced about the wording here... couldn't really decide what would be most useful when I sat down to improve the wording. I hope the additional example would have helped former me.

2017-01-03 16:12 UTC, obrok requested changes

2017-01-03 16:12 UTC, obrok commented on lib/lens.ex
> +  Returns a lens that focuses on all of the data in the given scope.
I don't really like this "scope" - I don't think there is a mention of "scope" anywhere else in the doc. "all of the" vs. "the whole" is a good change, I think.

2017-01-04 09:36 UTC, sebastian commented on lib/lens.ex
> +  Returns a lens that focuses on all of the data in the given scope.
But "all of the data" by itself is no less confusing. The problem which confused me was exactly that it wasn't _all of the data_ (which would have been the the `root` of the whole data structure), but rather the subtree that is currently focused on.

Do you have a suggestion for a better wording?

2017-01-04 09:38 UTC, sebastian commented on lib/lens.ex
> +  Returns a lens that focuses on all of the data in the given scope.
How about:

> Returns a lens that yields the entirety of the data currently under focus.

2017-01-04 11:28 UTC, obrok commented on lib/lens.ex
> +  Returns a lens that focuses on all of the data in the given scope.
> Returns a lens that yields the entirety of the data currently under focus.

This sounds good to me. Does it address the problem you have? You could also split it into 2 sentences, one saying the general "all the data" thing and the other describing the behaviour in a chain of lenses.

2017-01-04 13:22 UTC, sebastian commented on lib/lens.ex
> +  Returns a lens that focuses on all of the data in the given scope.
Yes, I think that would have solved my problem.

2017-01-04 13:22 UTC, sebastian commented
Ready for re-reveiw

2017-01-04 13:24 UTC, merged